### ISSUE TITLE
error creating a wheel file

### ISSUE THREAD

**Issue by sdolenc** [WorksApplications/SudachiDict#27]
I'm seeing an error when I attempt to create a whl file on linux

```
git checkout tags/v20201223
env_name=$(basename $(pwd))
ANACONDA_DIR="${HOME}/anaconda"
source $ANACONDA_DIR/etc/profile.d/conda.sh
conda create -n $env_name python=3.7 -y
conda activate $env_name
cd python/
```
I've tried both `pip wheel .` and `python setup.py bdist_wheel` on the latest commit and also the latest tag, but I get this error

```
Downloading the Sudachi dictionary (It may take a while) ...
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    _, _msg = urlretrieve(ZIP_URL, ZIP_NAME)
  File "/home/localstepdo/anaconda/envs/SudachiDict/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/localstepdo/anaconda/envs/SudachiDict/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/localstepdo/anaconda/envs/SudachiDict/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/localstepdo/anaconda/envs/SudachiDict/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/localstepdo/anaconda/envs/SudachiDict/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/localstepdo/anaconda/envs/SudachiDict/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/localstepdo/anaconda/envs/SudachiDict/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Invalid URI: isHexDigit
```

Any advice would be greatly appreciated

**Comment by kazuma-t** [comment]
The Python package has no contents and the data itself is downloaded from elsewhere. Since that location has changed, we need to use the current source for past packages instead of the past source.

You can create it by using package_python.sh as follows,

```
$ sh package_python.sh 20201223
```

**Comment by sdolenc** [comment]
thanks!!

In case others have any trouble:
```
git checkout tags/v20201223
bash package_python.sh 20201223
pushd ./build/python/20201223/core/
python setup.py bdist_wheel
pushd ./dist
ls
```

**Comment by sdolenc** [comment]
update: the best way to generate a wheel file
1. download tar.gz of the version you want from pypi. for example: https://pypi.org/project/SudachiDict-core/20201223.post1/#files
2. uncompress
3. then run `python setup.py bdist_wheel`
